INSERT INTO category (name) VALUES ('American');
INSERT INTO category (name) VALUES ('Italian');
INSERT INTO category (name) VALUES ('Mexican');
INSERT INTO category (name) VALUES ('Fast Food');
INSERT INTO unit_of_measure (oum) VALUES ('Teaspoon');
INSERT INTO unit_of_measure (oum) VALUES ('Tablespoon');
INSERT INTO unit_of_measure (oum) VALUES ('Cup');
INSERT INTO unit_of_measure (oum) VALUES ('Pinch');
INSERT INTO unit_of_measure (oum) VALUES ('Ounce');
INSERT INTO unit_of_measure (oum) VALUES ('Dash');
